#!/usr/bin/env bash
# Render WoWSimpleRegistration config.php from environment variables.
set -euo pipefail

CONFIG_DIR="/var/www/html/application/config"
CONFIG_FILE="${CONFIG_DIR}/config.php"

DB_HOST="${DB_HOST:-db}"
DB_PORT="${DB_PORT:-3306}"
DB_USER="${DB_USER:-mangos}"
DB_PASSWORD="${DB_PASSWORD:-mangos}"
DB_LOGIN="${DB_LOGIN:-tw_logon}"
DB_CHAR="${DB_CHAR:-tw_char}"

REALM_ID="${REALM_ID:-1}"
REALM_NAME="${REALM_NAME:-TurtleWoW}"
REALM_ADDRESS="${REALM_ADDRESS:-127.0.0.1}"

WSR_BASEURL="${WSR_BASEURL:-http://localhost}"
WSR_PAGE_TITLE="${WSR_PAGE_TITLE:-Turtle WoW Registration}"
WSR_LANGUAGE="${WSR_LANGUAGE:-english}"
WSR_REALMLIST="${WSR_REALMLIST:-${REALM_ADDRESS}}"
WSR_PATCH_LOCATION="${WSR_PATCH_LOCATION:-}"
WSR_GAME_VERSION="${WSR_GAME_VERSION:-1.18.1}"
WSR_EXPANSION="${WSR_EXPANSION:-0}"
WSR_SERVER_CORE="${WSR_SERVER_CORE:-5}"
WSR_BATTLEGROUNDS_SUPPORT="${WSR_BATTLEGROUNDS_SUPPORT:-false}"
WSR_SRP6_SUPPORT="${WSR_SRP6_SUPPORT:-true}"
WSR_SRP6_VERSION="${WSR_SRP6_VERSION:-2}"

WSR_DISABLE_TOP_PLAYERS="${WSR_DISABLE_TOP_PLAYERS:-false}"
WSR_DISABLE_ONLINE_PLAYERS="${WSR_DISABLE_ONLINE_PLAYERS:-false}"
WSR_DISABLE_CHANGEPASSWORD="${WSR_DISABLE_CHANGEPASSWORD:-false}"
WSR_MULTIPLE_EMAIL_USE="${WSR_MULTIPLE_EMAIL_USE:-false}"

WSR_TEMPLATE="${WSR_TEMPLATE:-light}"

WSR_SMTP_HOST="${WSR_SMTP_HOST:-}"
WSR_SMTP_PORT="${WSR_SMTP_PORT:-587}"
WSR_SMTP_AUTH="${WSR_SMTP_AUTH:-true}"
WSR_SMTP_USER="${WSR_SMTP_USER:-}"
WSR_SMTP_PASS="${WSR_SMTP_PASS:-}"
WSR_SMTP_SECURE="${WSR_SMTP_SECURE:-tls}"
WSR_SMTP_MAIL="${WSR_SMTP_MAIL:-}"

WSR_CAPTCHA_TYPE="${WSR_CAPTCHA_TYPE:-0}"
WSR_CAPTCHA_KEY="${WSR_CAPTCHA_KEY:-}"
WSR_CAPTCHA_SECRET="${WSR_CAPTCHA_SECRET:-}"
WSR_CAPTCHA_LANGUAGE="${WSR_CAPTCHA_LANGUAGE:-en}"

WSR_SOAP_FOR_REGISTER="${WSR_SOAP_FOR_REGISTER:-false}"
WSR_SOAP_HOST="${WSR_SOAP_HOST:-127.0.0.1}"
WSR_SOAP_PORT="${WSR_SOAP_PORT:-7878}"
WSR_SOAP_URI="${WSR_SOAP_URI:-urn:MaNGOS}"
WSR_SOAP_STYLE="${WSR_SOAP_STYLE:-SOAP_RPC}"
WSR_SOAP_USERNAME="${WSR_SOAP_USERNAME:-admin_soap}"
WSR_SOAP_PASSWORD="${WSR_SOAP_PASSWORD:-admin_soap}"

WSR_2FA_SUPPORT="${WSR_2FA_SUPPORT:-false}"

mkdir -p "${CONFIG_DIR}"

cat > "${CONFIG_FILE}" <<PHP
<?php
/**
 * Configuration for the web interface of a World of Warcraft private server.
 * Auto-generated by render-config.sh — edits will be overwritten on container start.
 */

// Basic Configuration
\$config['baseurl'] = "${WSR_BASEURL}";
\$config['page_title'] = "${WSR_PAGE_TITLE}";
\$config['language'] = "${WSR_LANGUAGE}";
\$config['supported_langs'] = [
    'english' => 'English',
    'persian' => 'Persian',
    'italian' => 'Italian',
    'chinese-simplified' => 'Chinese Simplified',
    'chinese-traditional' => 'Chinese Traditional',
    'swedish' => 'Swedish',
    'french' => 'French',
    'german' => 'German',
    'spanish' => 'Spanish',
    'korean' => 'Korean',
    'russian' => 'Russian',
    'portugues' => 'Portuguese',
];

\$config['debug_mode'] = false;

// Server Information
\$config['realmlist'] = '${WSR_REALMLIST}';
\$config['patch_location'] = '${WSR_PATCH_LOCATION}';
\$config['game_version'] = '${WSR_GAME_VERSION}';
\$config['expansion'] = '${WSR_EXPANSION}';
\$config['server_core'] = ${WSR_SERVER_CORE};
\$config['battlenet_support'] = ${WSR_BATTLEGROUNDS_SUPPORT};
\$config['srp6_support'] = ${WSR_SRP6_SUPPORT};
\$config['srp6_version'] = ${WSR_SRP6_VERSION};

// Feature Toggles
\$config['disable_top_players'] = ${WSR_DISABLE_TOP_PLAYERS};
\$config['disable_online_players'] = ${WSR_DISABLE_ONLINE_PLAYERS};
\$config['disable_changepassword'] = ${WSR_DISABLE_CHANGEPASSWORD};
\$config['multiple_email_use'] = ${WSR_MULTIPLE_EMAIL_USE};

// Template Selection
\$config['template'] = '${WSR_TEMPLATE}';

// SMTP Configuration
\$config['smtp_host'] = '${WSR_SMTP_HOST}';
\$config['smtp_port'] = ${WSR_SMTP_PORT};
\$config['smtp_auth'] = ${WSR_SMTP_AUTH};
\$config['smtp_user'] = '${WSR_SMTP_USER}';
\$config['smtp_pass'] = '${WSR_SMTP_PASS}';
\$config['smtp_secure'] = '${WSR_SMTP_SECURE}';
\$config['smtp_mail'] = '${WSR_SMTP_MAIL}';

// Vote System Configuration
\$config['vote_system'] = false;
\$config['vote_sites'] = array();

// Captcha Configuration
\$config['captcha_type'] = ${WSR_CAPTCHA_TYPE};
\$config['captcha_key'] = '${WSR_CAPTCHA_KEY}';
\$config['captcha_secret'] = '${WSR_CAPTCHA_SECRET}';
\$config['captcha_language'] = '${WSR_CAPTCHA_LANGUAGE}';

// SOAP Interface for Account Registration
\$config['soap_for_register'] = ${WSR_SOAP_FOR_REGISTER};
\$config['soap_host'] = '${WSR_SOAP_HOST}';
\$config['soap_port'] = '${WSR_SOAP_PORT}';
\$config['soap_uri'] = '${WSR_SOAP_URI}';
\$config['soap_style'] = '${WSR_SOAP_STYLE}';
\$config['soap_username'] = '${WSR_SOAP_USERNAME}';
\$config['soap_password'] = '${WSR_SOAP_PASSWORD}';
\$config['soap_ca_command'] = 'account create {USERNAME} {PASSWORD}';

// Two-Factor Authentication (2FA)
\$config['2fa_support'] = ${WSR_2FA_SUPPORT};
\$config['soap_2d_command'] = 'account set 2fa {USERNAME} off';
\$config['soap_2e_command'] = 'account set 2fa {USERNAME} {SECRET}';

// Database Information
\$config['db_auth_host'] = '${DB_HOST}';
\$config['db_auth_port'] = '${DB_PORT}';
\$config['db_auth_user'] = '${DB_USER}';
\$config['db_auth_pass'] = '${DB_PASSWORD}';
\$config['db_auth_dbname'] = '${DB_LOGIN}';

// Realmlist Configuration
\$config['realmlists'] = array(
    "${REALM_ID}" => array(
        'realmid' => ${REALM_ID},
        'realmname' => "${REALM_NAME}",
        'db_host' => "${DB_HOST}",
        'db_port' => "${DB_PORT}",
        'db_user' => "${DB_USER}",
        'db_pass' => '${DB_PASSWORD}',
        'db_name' => "${DB_CHAR}",
    ),
);

\$config['script_version'] = '2.0.2';
PHP

echo "WoWSimpleRegistration config rendered to ${CONFIG_FILE}"
