# REPO_URL|FOLDER_NAME|BRANCH
# https://github.com/PiotrZadka/TortoiseBots.git|TortoiseBots|main
https://github.com/Penqle/tw-mod-autoscale.git|tw-mod-autoscale|main
https://github.com/Penqle/tw-mod-leech.git|tw-mod-leech|master
https://github.com/dr1s/tw-mod-hearthstone-cooldown.git|tw-mod-hearthstone-cooldown|main
# https://github.com/FiraVT/Mod-aoe-loot-tortoiseport.git|mod-aoe-loot|main
